host: q.toki317.dev

backend:
  image: ghcr.io/traptitech/traq:3.26.1
  nodeSelector:
    kubernetes.io/hostname: moto-a1-3
  env:
    # https://github.com/aws/aws-sdk-go-v2/discussions/2960
    # https://gitlab.com/gitlab-org/charts/gitlab/-/issues/6094
    AWS_REQUEST_CHECKSUM_CALCULATION: WHEN_REQUIRED

es:
  image: ghcr.io/traptitech/es-with-sudachi:8.8.1-3.1.0
  nodeSelector:
    kubernetes.io/hostname: moto-a1-3
  
frontend:
  image: ghcr.io/traptitech/traq-ui:3.29.0
  nodeSelector:
    kubernetes.io/hostname: moto-a1-3

widget:
  image: ghcr.io/traptitech/traq-widget:0.3.7
  nodeSelector:
    kubernetes.io/hostname: moto-a1-3

systemBot:
  image: ghcr.io/traptitech/traq-system-bot:1.1.0
  nodeSelector:
    kubernetes.io/hostname: moto-a1-3
  channelId: 0e10c15a-f147-4fbe-a85d-bde865c3861c
