resources:
  # renovate:github-url
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.17.0/crd.yaml
  # renovate:github-url
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.17.0/system-upgrade-controller.yaml
  - server-plan.yaml
  - agent-plan.yaml
