helmCharts:
  - repo: https://victoriametrics.github.io/helm-charts/
    name: victoria-logs-single
    version: "0.11.20"
    includeCRDs: true
    namespace: victoria-logs
    releaseName: vl
    valuesFile: values.yaml

resources:
  - datasource-cm.yaml
