domain: ""
clientID: ""
secretName: ""

cookieName: "_forward_auth"
headerNames:
  - X-Forwarded-User
  - X-Showcase-User

image:
  name: "ghcr.io/traptitech/traefik-forward-auth"
  # image datasource=docker depName=ghcr.io/traptitech/traefik-forward-auth registryUrl=ghcr.io
  tag: "2.6.3"
