image:
  name: "ghcr.io/traptitech/traefik-forward-auth"
  # renovate:image-tag imageName=ghcr.io/traptitech/traefik-forward-auth
  tag: "3.3.3"

authHosts: []
hosts: []

replicas: 2
pdb:
  enabled: true
  minAvailable: 1

ingressRoute:
  enabled: true
  entrypoints:
    - websecure
  tlsName: ""

oidc:
  clientID: ""
  scopes: "openid"
  issuerUrl: "https://q.toki317.dev"
  prompt: none

secretName: "forward-auth"

cookie:
  name: "_forward_auth"
  lifetime: 1209600 # 2 weeks

infoFields:
  - name
headers:
  - name: X-Forwarded-User
    source: name
