helmCharts:
  - repo: https://helm.goharbor.io
    name: harbor
    # renovate:general datasource=helm depName=harbor registryUrl=https://helm.goharbor.io
    version: "1.18.1"
    includeCRDs: true
    namespace: harbor
    releaseName: harbor
    valuesFile: values.yaml

resources:
  - certificate.yaml
  - ingress-route.yaml
  - service-account.yaml

generators:
  - ksops.yaml
